services:
  database:
    image: postgres:latest
    restart: always
    environment: 
      POSTGRES_USER: "caffeine"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    networks:
      - mynet
    volumes:
      - data:/var/lib/postgresql/data1
  unirest:
    image: xdung24/unirest:latest
    environment:
        DB_TYPE: postgres 
        PG_HOST: database 
        PG_USER: "unirest"
        PG_PASS: "SecureP@ssw0rd"
    networks:
      - mynet
    ports:
    - "8000:8000"
 
volumes:
  data:

networks:
  mynet:
    driver: bridge
